package iuh.fit.se.analyticsservice.dto.event;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * User Registered Event
 * 
 * Published by User Service when a new user registers.
 * Consumed by Analytics Service to track new registrations.
 * 
 * @author OTT Platform Team
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UserRegisteredEvent implements Serializable {
    
    /**
     * Unique event identifier for idempotency
     * Generated by publisher before sending to RabbitMQ
     */
    private String eventId;
    
    /**
     * Registered user ID
     */
    private UUID userId;
    
    /**
     * User's phone number
     */
    private String phone;
    
    /**
     * User's email address
     */
    private String email;
    
    /**
     * Registration method: "GOOGLE" or "LOCAL"
     */
    private String registrationMethod;
    
    /**
     * Registration timestamp
     */
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private LocalDateTime timestamp;
}
